---
title: "Themenübersicht - R Interfaces"
author: "Jan-Philipp Kolb"
date: "08 Mai 2017"
output: 
  md_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## [Schnittstellen für den Austausch von Daten](https://github.com/Japhilko/RInterfaces/blob/master/slides/RInterfaces_all2g_1.md)

- [Einführung und Motivation](https://github.com/Japhilko/RInterfaces/blob/master/slides/Intro.md) ([pdf](slides/Intro.pdf))

Aufgabe: [Zusatzpakete](tutorial/Aufgabe_Zusatzpakete.Rmd)

- [Datenimport](slides/Datenimport.md) ([pdf](slides/Datenimport.pdf) | [rcode](slides/Datenimport.R))

Aufgabe: [Datenimport](tutorial/Datenimport.Rmd)

- [Datenexport](slides/Datenexport.md) ([pdf](slides/Datenexport.pdf) | [rcode](slides/Datenexport.R)) 
- [R und Excel](slides/Rexcel.md) ([pdf](Rexcel.pdf) | [rcode](slides/Rexcel.R))

## [Präsentation von Daten - Reproducible Research](https://github.com/Japhilko/RInterfaces/blob/master/slides/RInterfaces_all2g_2.md)

- [Word Dokumente mit R erstellen](slides/R2word.md) ([pdf](slides/R2word.pdf))
-	[PDF Dokumente und Präsentationen mit LaTeX, Beamer und Sweave](slides/R2pdf.md) ([pdf](slides/R2pdf.pdf))
-	[HTML Dokumente, Präsentationen und Dashboards mit Rmarkdown](slides/Rmarkdown.md) ([pdf](slides/Rmarkdown.pdf))
- [Notebooks](slides/Notebooks.md) zur Integration von anderen Programmiersprachen (Python,LaTeX,Julia) ([pdf](slides/Notebooks.pdf))

Aufgabe: Bearbeiten Sie ein Notebook weiter

## [Interaktive Darstellung mit Javascript und R](https://github.com/Japhilko/RInterfaces/blob/master/slides/RInterfaces_all2g_3.md)

-	[Interaktive Karten mit dem Javascript Paket leaflet](https://github.com/Japhilko/RInterfaces/blob/master/slides/leaflet.md)
-	[Interaktive Tabellen mit DataTables](https://github.com/Japhilko/RInterfaces/blob/master/slides/DataTables.md)
-	[R und die Javascript Data-Driven Documents (D3)](https://github.com/Japhilko/RInterfaces/blob/master/slides/D3.md)
-	[Interaktive Graphiken mit D3 und plotly](https://github.com/Japhilko/RInterfaces/blob/master/slides/plotly.md)

-	[Netzwerkgraphiken mit vis.js](https://github.com/Japhilko/RInterfaces/blob/master/slides/visNetwork.md)
-	[Das Erstellen von Ablaufdiagrammen mit mermaid](https://github.com/Japhilko/RInterfaces/blob/master/slides/mermaid.md)



## [Internetresourcen und Schnittstellen nutzen](https://github.com/Japhilko/RInterfaces/blob/master/slides/RInterfaces_all2g_4.md)

-	[Import von JSON-Objekten und XML Dateien](slides/rapis.Rmd) ([pdf](slides/rapis.pdf) | [rcode](slides/rapis.pdf))
- [Die Pakete rvest und RCurl](slides/rvest.md)
- [Webscraping](https://github.com/Japhilko/RInterfaces/blob/master/slides/Webscraping.md)
- [Use Case - Scraping Wikipedia](slides/ScrapingWikipedia.Rmd)


## [Applikationen und Projektverwaltung mit Rstudio und git](https://github.com/Japhilko/RInterfaces/blob/master/slides/RInterfaces_all2g_5.md)

- [Allgemein zur Versionsverwaltung](slides/Versionsverwaltung.Rmd)
- [R und Git](slides/Rgit.Rmd)
- [Shiny Apps](slides/shiny.Rmd)


## [Hochperfomanter Code](https://github.com/Japhilko/RInterfaces/blob/master/slides/RInterfaces_all2g_6.md)

-	[C++ Integration - Überblick über das Paket rcpp](https://github.com/Japhilko/RInterfaces/blob/master/slides/rcpp.md)
-	Überblick über Möglichkeiten des Parallel Computings - Paket parallel

## [Integration von Datenbanken](https://github.com/Japhilko/RInterfaces/blob/master/slides/RInterfaces_all2g_7.md)

- [Datenbanken und R](slides/Datenbanken.Rmd)
- [Das R-Paket `dplyr`](slides/dplyr.Rmd)
-	[Integration von PostgreSQL mit dem Paket 
RPostgreSQL](https://github.com/Japhilko/RInterfaces/blob/master/slides/RPostgreSQL.Rmd)
-	[Nutzung von weiteren Datenbanken (MongoDB, MySQL)]((https://github.com/Japhilko/RInterfaces/blob/master/slides/Rmongodb.md))





