---
title: "Das DiagrammeR Paket"
author: "Jan-Philipp Kolb"
date: "8 Mai 2017"
output: 
  slidy_presentation: 
    keep_md: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Um was geht es?

- [Der Start](http://rich-iannone.github.io/DiagrammeR/docs.html)

- [Das R-Paket DiagrammeR](http://rich-iannone.github.io/DiagrammeR/index.html)

```{r,eval=F}
install.packages('DiagrammeR')
```



```{r}
library('DiagrammeR')
```


## Eine einfache Grafik erzeugen

```{r}
DiagrammeR("
  graph LR
    A-->B
    A-->C
    C-->E
    B-->D
    C-->D
    D-->F
    E-->F
")
```

## [Ein GANTT Diagramm erstellen](https://knsv.github.io/mermaid/#mermaid)

```{r}
DiagrammeR("
gantt
        dateFormat  YYYY-MM-DD
        title Adding GANTT diagram functionality to mermaid
        section A section
        Completed task            :done,    des1, 2014-01-06,2014-01-08
        Active task               :active,  des2, 2014-01-09, 3d
        Future task               :         des3, after des2, 5d
        Future task2               :         des4, after des3, 5d
        section Critical tasks
        Completed task in the critical line :crit, done, 2014-01-06,24h
        Implement parser and jison          :crit, done, after des1, 2d
        Create tests for parser             :crit, active, 3d
        Future task in critical line        :crit, 5d
        Create tests for renderer           :2d
        Add to mermaid                      :1d
")
```

## Ein weiteres Gantt Diagramm

```{r}
library(DiagrammeR)
mermaid("
gantt
dateFormat  YYYY-MM-DD
title A Very Nice Gantt Diagram

section Basic Tasks
This is completed             :done,          first_1,    2014-01-06, 2014-01-08
This is active                :active,        first_2,    2014-01-09, 3d
Do this later                 :               first_3,    after first_2, 5d
Do this after that            :               first_4,    after first_3, 5d

section Important Things
Completed, critical task      :crit, done,    import_1,   2014-01-06,24h
Also done, also critical      :crit, done,    import_2,   after import_1, 2d
Doing this important task now :crit, active,  import_3,   after import_2, 3d
Next critical task            :crit,          import_4,   after import_3, 5d

section The Extras
First extras                  :active,        extras_1,   after import_4,  3d
Second helping                :               extras_2,   after extras_1, 20h
More of the extras            :               extras_3,   after extras_1, 48h
")
```



## Links

- [Github repo](https://github.com/knsv/mermaid)

- [Gantt chart](http://stackoverflow.com/questions/3550341/gantt-charts-with-r)

- [Javascript Bibliothek mermaid](https://knsv.github.io/mermaid/)

- [viz.js](https://github.com/mdaines/viz.js)
